### ISSUE TITLE
mvn grails:maven-war doesn't work without explicit net.bull.javamelody:javamelody-core dependency

### ISSUE THREAD

**Issue by evernat** [javamelody/grails-melody-plugin#2]
Moved from https://code.google.com/p/javamelody/issues/detail?id=284

I'm trying to use grails-melody:1.13 Grails plugin with maven. I have defined plugin in pom.xml. 
mvn -Dgrails.env=dev grails:maven-war throws an exception:
GrailsDataSourceBeanPostProcessor.groovy: 3: unable to resolve class net.bull.javamelody.JdbcWrapper

I can fix it by adding net.bull.javamelody:javamelody-core explicitly:
        <dependency>
            <groupId>net.bull.javamelody</groupId>
            <artifactId>javamelody-core</artifactId>
            <version>1.36.0</version>
        </dependency>

Why should I add it to pom.xml?

**Comment by sergiomichels** [comment]
Closing as this reference an old version of Grails and JavaMelody.
