### ISSUE TITLE
Add Grails 3 support and publish to Bintray

### ISSUE THREAD

**Issue by dpilafian** [javamelody/grails-melody-plugin#25]
It would be helpful to have the JavaMelody Grails Plugin listed at:
   * https://bintray.com/grails/plugins

I was able to get the plugin to download by adding the dependency to the build file:

**build.gradle**

    compile "net.bull.javamelody:javamelody-core:1.56.0"

However, a 404 results when attempting to open the console:

   * [http://localhost:8080/monitoring](http://localhost:8080/monitoring)

**Environment:**

    $ grails --version
    | Grails Version: 3.0.3
    | Groovy Version: 2.4.3
    | JVM Version: 1.8.0_51
    $ uname -a
    Darwin Blade.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

**Comment by evernat** [comment]
It seems that there is an [upgrade plugin doc](http://grails.github.io/grails-doc/latest/guide/upgrading.html)

For 404 on http://localhost:8080/<YourContext>/monitoring, I suppose that something with filters does not work in GrailsMelodyGrailsPlugin.groovy with Grails 3.

A pull request would be great.

**Comment by sergiomichels** [comment]
```doWithWebDescriptor``` is not available anymore, so we need to convert it to [the Spring Boot way](http://stackoverflow.com/questions/26639475/how-to-set-context-param-in-spring-boot).

I will try to work in this migration on my free time. If I finish it, could I just make a pull request to master or should a branch be created to Grails 3?

**Comment by evernat** [comment]
I think that a pull request is ok, since I don't plan to maintain two version in parallel.

About the Spring Boot way, you can see an example of javamelody in Spring Boot here:
https://github.com/javamelody/javamelody/blob/master/javamelody-for-spring-boot/src/main/java/hello/JavaMelodyConfiguration.java

**Comment by sergiomichels** [comment]
Thanks for the link, the filter worked! I'm almost done with a first version, just need more tests to confirm that I didn't break any feature.

**Comment by sergiomichels** [comment]
Found the first difference. In Grails 2.x ```MonitoringProxy.getSpringCounter().isDisplayed()``` returns ```true``` but not in Grails 3.x.

**Comment by evernat** [comment]
The call to SPRING_COUNTER.isDisplayed() in GrailsMelodyGrailsPlugin.groovy should be changed as part of PR #28, if it is the problem here.

**Comment by sergiomichels** [comment]
Yep, #28 fixed it.

**Comment by sergiomichels** [comment]
@dpilafian can you try my snapshot? https://github.com/sergiomichels/grails-melody-plugin

**Comment by akozel** [comment]
Will that appear in bintray.com? What should we do to install the plugin at grails 3? Help.

**Comment by sergiomichels** [comment]
Download as zip and do an local install in your maven, then it will be available to you.

**Comment by akozel** [comment]
thank you. I managed to install that. Please add that to official repository.

Also tere s small guide how to install melogy.
1. [download zip](https://github.com/sergiomichels/grails-melody-plugin)
2. add to plugins folder the '.gradle' and 'gradle' folders (you can get it from yours proj)
3. go to plugns folder via console and run gradlew.bat install
4. Now plugin installed into your maven. For example I can find it here (by default):
`(C:\Users\_your_username_\.m2\repository\org\grails\plugins)`
5. add dependency to your project
`'runtime 'org.grails.plugins:grails-melody-plugin-master:2.0-SNAPSHOT'`

6. Dont forget to configure spring sequripy plugin (if installed)
`grails.plugin.springsecurity.controllerAnnotations.staticRules = [
        [pattern: '/monitoring', access: ['ROLE_ADMIN']]
]`

**Comment by sergiomichels** [comment]
Plugin [uploaded to Bintray](https://bintray.com/sergiomichels/plugins/grails-melody-plugin/view)

Waiting now to see it appears in the official repository (request sent).
