### ISSUE TITLE
Getting grails melody work with grails 3

### ISSUE THREAD

**Issue by odimou** [javamelody/grails-melody-plugin#30]
Hello,
I tried to install with adding the exist lines to build.gradle. 
`
compile "net.bull.javamelody:javamelody-core:1.59.0"`
`
compile "org.grails.plugins:grails-melody:1.59.0"
`
I'm getting error on resolving dependencies for the grails-melody plugin. Any idea? I'm using grails 3.0.10.
Thanks

**Comment by sergiomichels** [comment]
Please check https://github.com/javamelody/grails-melody-plugin/issues/25, can you help us with tests?
