### ISSUE TITLE
Exceptions in grails melody plugin with some particular service parameter definitions

### ISSUE THREAD

**Issue by evernat** [javamelody/grails-melody-plugin#4]
Moved from https://code.google.com/p/javamelody/issues/detail?id=165

What steps will reproduce the problem?
See http://groups.google.com/group/javamelody/browse_thread/thread/130738bdfc5a50e8 and the end of http://jira.grails.org/browse/GPMELODY-1

What is the expected output? What do you see instead?
The services should be executed like when grails melody plugin is not installed. Instead, there are exceptions in the grails melody plugin as said above.

Additional information.
Fortunately, the links above give workarounds

**Comment by sergiomichels** [comment]
Closing since there's no update in this issue since 2013 :)
