### ISSUE TITLE
Sometimes Content-Type header missing

### ISSUE THREAD

**Issue by purpleraven** [javamelody/grails-melody-plugin#40]
With plugin version 1.62 sometimes Content-Type header missing for views without layout
Usually, a response has:

> Content-Type:text/html;charset=UTF-8
But for some tires of same page loading -- it's missing

I have tried to add to view following code -- no result

`<%@ page contentType="text/html;charset=UTF-8" %>`

After removing plugin everything works well 

Grails version 3.1.14

**Comment by demon101** [comment]
sorry, bug was produced not by plugin

**Comment by evernat** [comment]
ok, thanks
