### ISSUE TITLE
How to change url from /monitoring to /app-monitor

### ISSUE THREAD

**Issue by ferasodh** [javamelody/grails-melody-plugin#41]
Is it possible to change the java melody url from /monitoring to /app-monitor or any other url? How can I do that?

Thanks

**Comment by evernat** [comment]
Yes, it's possible. You need to use the javamelody parameter `monitoring-path` for that.

For the grails-melody-plugin, you can add in your grails-app/conf/application.yml:
```yml
javamelody:
    monitoring-path: /app-monitor
```
