### ISSUE TITLE
Outdated import in MelodyInterceptorEnhancer: net.bull.javamelody.Parameters

### ISSUE THREAD

**Issue by jukin-jerry** [javamelody/grails-melody-plugin#44]
Latest commits to master for upgrade to javamelody-core:1.68.0 misses one deprecated and relocated import:

`net.bull.javamelody.Parameters`
is now
`net.bull.javamelody.internal.common.Parameters`

Will provide a pull request.

**Comment by jukin-jerry** [comment]
Created https://github.com/javamelody/grails-melody-plugin/pull/45

**Comment by evernat** [comment]
merged
