### ISSUE TITLE
grails-melody-plugin must load after grails-quartz plugin to allow full reconfiguration of the scheduler thread

### ISSUE THREAD

**Issue by jukin-jerry** [javamelody/grails-melody-plugin#46]
If the grails-melody-plugin loads before the grails-quartz plugin, any re-configurations of the quartz scheduler thread in the Grails application do not happen when melody initializes, which results in the default scheduler thread always loading with the default configuration out of the box.  If the Grails application wants to have a different scheduler thread configuration, two are created, causing issues at application shutdown.

Simple solution is to include 'quartz' in the loadAfter property of the grails-melody plugin.

Will add pull request.

**Comment by jukin-jerry** [comment]
https://github.com/javamelody/grails-melody-plugin/pull/47

**Comment by evernat** [comment]
merged
