### ISSUE TITLE
Exception: Connection has already been closed

### ISSUE THREAD

**Issue by Relaximus** [javamelody/grails-melody-plugin#53]
With update to the 1.70.0 version of Melody. We avoided the #48 but it seems that we have got the jdbc connections leakage.

From our log:

Caused by SQLException: Connection has already been closed.
->>  197 | invoke           in net.bull.javamelody.JdbcWrapper$ConnectionInvocationHandler

We suppose, that we catch the bug here, because we are using pooled option in our Grails app datasource configuration. 

Comparing the log output of 1.67 and 1.70 we noticed that the 1.70 wraps one additional bean dataSourceUnproxied. Excluding this bean from wrapping seems helped as a workaround.

Could you check the BBP approach in conjunction with db pool enabled?

**Comment by sergiomichels** [comment]
@bassmartin Could you check it?

**Comment by bassmartin** [comment]
@sergiomichels see #52 
I think adding 'excludes' like I wrote in my ticket will fix this issue too.

**Comment by Relaximus** [comment]
@bassmartin That is interesting, because our workaround is other way around to exclude unproxied bean and it works. 
It seems that the problem, when Melody wrapper wraps itself twice. What do you think?

**Comment by bassmartin** [comment]
I think it really has to do with what you say "re-wrapping".

The test I was doing is to run my app, close my wi-fi (so DB was not accessible anymore), wait for tons of error to show, reconnect the wifi, expect the background jobs to work a expected and the UI to show queried data without any error.

Only proxying the 'unproxied' data sources would pass this test.

But this morning, in an integration environment, I seem to see the same issue happening again.

I will try your solution this PM.

**Comment by bassmartin** [comment]
I finished doing the same test with 'dataSource' being the only one not excluded from being proxied and it seem to be working...

I will push this to our integration env. to see if it's working there too.

**Comment by bassmartin** [comment]
I just tried only proxying 'dataSourceLazy' and it seems to pass my test. I've done it twice. I will continue to play with this.

resources.groovy
`    // Recreate the bean with excluded datasources
    springDataSourceBeanPostProcessor(SpringDataSourceBeanPostProcessor) {
        excludedDatasources = ['dataSourceUnproxied', 'dataSource']
    }`

**Comment by bassmartin** [comment]
The fix is still in our integration environment. So far so good.

**Comment by sergiomichels** [comment]
@bassmartin This fix is working for you, right? Could you open an PR?

**Comment by sergiomichels** [comment]
I've just created a sample app with latest Grails version and cannot see any sql statistics :(... 

I will try this config with `excludedDatasources` tomorrow.

**Comment by bassmartin** [comment]
The fix is working fine in my env. (Grails 3.2.x). I will create a PR if you still want it.

So we will need to create a new release line for Grails 3.3.x?

**Comment by sergiomichels** [comment]
I think we can maintain one version but if it's Grails 3.3.x we will need to load a different BeanPostProcessor.    No need for PR, I will test it for both versions :)

**Comment by bassmartin** [comment]
I recently upgraded to GORM 6.1+ and the fact that 

> EDIT - Looks like we cannot use SpringDataSourceBeanPostProcessor anymore. Grails uses now InstanceFactoryBean wrapping the DataSource proxies

is caused by GORM 6.1+, not Grails 3.3 per se (I'm still on Grails 3.2+)

**Comment by bassmartin** [comment]
Any progress on this issue? Or do you have some pointers so I can try to implement something to get SQL monitored again? Thanks.

**Comment by bassmartin** [comment]
I've put back the code in `GrailsMelodyPluginGrailsPlugin` that was there before switching back to `SpringDataSourceBeanPostProcessor`. I changed the `if` clause so it only wraps the `Lazy` datasource beans. SQL queries a monitored. I will check if after a while there are issues arising. (Grails 3.2.13 and Gorm 6.1.9).

`
  void doWithApplicationContext() {
        //Need to wrap the datasources here, because BeanPostProcessor didn't worked.
        def beans = getApplicationContext().getBeansOfType(DataSource)
        beans.each { beanName, bean ->
            if (beanName.contains('Lazy')) {
                LOG.debug "Wrapping DataSource - $beanName"
                bean.targetDataSource = JdbcWrapper.SINGLETON.createDataSourceProxy(bean.targetDataSource)
            }
        }
    }
`

**Comment by bassmartin** [comment]
Still no issue and queries are logged.

**Comment by sergiomichels** [comment]
Thanks @bassmartin, could you open an PR?

**Comment by bassmartin** [comment]
I will today.

**Comment by bassmartin** [comment]
See #61

**Comment by bassmartin** [comment]
No, I'm no using JNDI.
I'm using Grails 3.2.13 and Gorm 6.1.9
Can you test your simple project with that?

**Comment by bassmartin** [comment]
Might have to do with 

> Datasource Plugin Refactor
> In previous versions of Grails and GORM the multiple data sources support relied on Grails' data sources plugin. The logic for configuring multiple data sources has moved to GORM and as a result of major changes to the dataSources plugin, beans for the lazy and unproxied representation of a dataSource are no longer available.
> 
> The beans include:
> 
> dataSourceUnproxied
> 
> dataSourceLazy
> 
> If you are referencing these beans you will need to remove these references and unwrap the single dataSource proxy manually.

We might need to add a check on the Grails version and proxy either 'dataSourceLazy' in Grails <= 3.2 or 'dataSource' in Grails >= 3.3 ?!?!

**Comment by bassmartin** [comment]
I created #62 that first attempt 'Lazy' beans then fallbacks on 'dataSource' if no 'Lazy' found. So it should support Grails <=3.2 as well as Grails >= 3.3

**Comment by sergiomichels** [comment]
Thanks @bassmartin, I've tested here and is logging sql info now.
