### ISSUE TITLE
﻿﻿No value for key [org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy] bound to thread

### ISSUE THREAD

**Issue by brischniz** [javamelody/grails-melody-plugin#65]
I tried to integrate the grails-melody-plugin-1.73.2 into a Grails-3.3.8 application but with some GORM interactions I got the following stacktrace:

```
java.lang.IllegalStateException: No value for key [org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy@64e3d4ab] bound to thread [pool-2-thread-1]
	at org.springframework.transaction.support.TransactionSynchronizationManager.unbindResource(TransactionSynchronizationManager.java:210)
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doCleanupAfterCompletion(HibernateTransactionManager.java:654)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.cleanupAfterCompletion(AbstractPlatformTransactionManager.java:1021)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:815)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:734)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:150)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
...
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
	at grails.melody.plugin.MelodyInterceptorEnhancer$_enhance_closure1$_closure2.doCall(MelodyInterceptorEnhancer.groovy:77)
	at sun.reflect.GeneratedMethodAccessor349.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
...
```
It seems that Graeme Rocher investigated on that issue a while ago: https://github.com/grails/grails-core/issues/10675#issuecomment-315321643

> This is an issue with the melody plugin. It is replacing the data source with another proxy which interferes with the references GORM uses to bind and unbind the session.

**Comment by sergiomichels** [comment]
@brischniz Could you provide a sample application with the issue? Probably it's related to #61.

**Comment by bassmartin** [comment]
I confirm this is happening.

I'll try to investigate.

**Comment by joemccall86** [comment]
Were you by any chance successful in creating a sample application? It might be easier to lobby for some help if we can reproduce it reliably.

**Comment by joemccall86** [comment]
Added sample here: https://github.com/joemccall86/melody-sample

**Comment by sergiomichels** [comment]
Thanks @joemccall86, I'll take a look at sample code.

**Comment by sergiomichels** [comment]
I've created branch 65_no_value_for_key, I see issue even without `ExpandoMetaClass.enableGlobally()`. In this branch I'm creating a new integration test app so we can improve our regression suite and avoid this issues in future.

**Comment by bassmartin** [comment]
Thanks Sergio! I just had a new baby so I don’t have much time right now ;-)

**Comment by sergiomichels** [comment]
@bassmartin Congratulations on the birth of your baby! Enjoy this time :-)

**Comment by bassmartin** [comment]
When I use the latest release, I don't have any SQL queries monitored.

sql Statistics sql - 1 day

None


Do you all still have SQL queries monitored?

**Comment by bassmartin** [comment]
I installed a custom version with this code modified (removed the if `if (dataSource instanceof TransactionAwareDataSourceProxy) {` and it works for me on Grails 3.3.9 and GORM 6.1.11... 

Why is that if required?

```
 // Attempt DataSources for Grails 3.3 and newer if no lazy proxy created
        if (!lazyProxied) {
            String hibernateBeanName = 'hibernateDatastore'
            if (applicationContext.containsBean(hibernateBeanName)) {
                def bean = applicationContext.getBean(hibernateBeanName)
                def transactionManager = bean.transactionManager
                def dataSource = transactionManager.dataSource
                LOG.debug "Wrapping Hibernate DataStore DataSource"
                dataSource.targetDataSource = JdbcWrapper.SINGLETON.createDataSourceProxy(dataSource.targetDataSource)
            }
        }
```

**Comment by sergiomichels** [comment]
Which class is this for you? I think my initial idea was to make sure that we're dealing with two levels of encapsulation to reach the datasource (store - targetds - targetds) but I guess we can check if property with this name exists instead of using instance of.

**Comment by bassmartin** [comment]
<img width="472" alt="screen shot 2019-01-02 at 10 54 49" src="https://user-images.githubusercontent.com/10145772/50600054-e2c87680-0e7d-11e9-92e4-b46df18bcb64.png">

**Comment by bassmartin** [comment]
This might have to do with my configuration.

Here are some extracts : 

```
grails:
    spring:
        transactionManagement:
            proxies: false

hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: true
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    flush:
        mode: AUTO
    jdbc:
        batch_versioned_data: false
        batch_size: 50
    connection:
        release_mode: ON_CLOSE
    hibernateDirtyChecking: true
```

**Comment by bassmartin** [comment]
Since the code in org.grails.datastore.gorm.jdbc.connections.DataSourceConnectionSourceFactory#proxy is 

```
    protected DataSource proxy(DataSource dataSource, DataSourceSettings settings) {
        if(settings.isLazy()) {
            dataSource = new LazyConnectionDataSourceProxy(dataSource);
        }
        if(settings.isTransactionAware()) {
            dataSource = new TransactionAwareDataSourceProxy(dataSource);
        }
        return dataSource;
    }
```

I think we could replace `if (dataSource instanceof TransactionAwareDataSourceProxy)` by `if (dataSource instanceof DelegatingDataSource)` to support both types of proxy (since it's the superclass of both).

What do you think about that @sergiomichels ?

**Comment by sergiomichels** [comment]
Yep, looks good. I think that probably there's an way to configure this for one specific integration test (instead of creating new project), can you take a look at Spring Security plug-in and see if it's using it? https://github.com/grails-plugins/grails-spring-security-core/tree/master/integration-test-app
