### ISSUE TITLE
No sql query logs for grails 3.3.9 + melody plugin 1.74

### ISSUE THREAD

**Issue by demon101** [javamelody/grails-melody-plugin#69]
After update to grails 3.3.9 from 3.2 version melody sql log is empty

Can it be related to  https://github.com/javamelody/grails-melody-plugin/issues/65 ? 

We are using only one standard data source with PostgreSQL DB.  

JDBC connections shows 0. 
![image](https://user-images.githubusercontent.com/1362920/51683370-fe8ceb80-1fe9-11e9-83f6-6c94c1e97e3d.png)

Usual tomcat JDBC pool used. During upgrade dependancy has been added
`runtime "org.apache.tomcat:tomcat-jdbc"`

**Comment by demon101** [comment]
problem was coused by 
`runtime "org.apache.tomcat:tomcat-jdbc"`

**Comment by demon101** [comment]
As I can see, tomcat-jdbc is a part of a newly created grails 3.3 app
But for me, java melody sql stat not working with the dependency.

**Comment by sergiomichels** [comment]
HI @demon101, you tried in an newly created app without changing anything? Would you be able to provide repo with sample app?
